In [1]:
import torch

In [2]:
x = torch.rand(2,2)

In [3]:
x

tensor([[0.8979, 0.9931],
        [0.6425, 0.4532]])

In [4]:
x.lt(0.5)

tensor([[0, 0],
        [0, 1]], dtype=torch.uint8)

In [6]:
3.12*x.lt(0.5)

tensor([[0, 0],
        [0, 3]], dtype=torch.uint8)

In [8]:
3*x.lt(0.5)

tensor([[0, 0],
        [0, 3]], dtype=torch.uint8)

In [9]:
def twos_complement(input_value, num_bits):
	'''Calculates a two's complement integer from the given input value's bits'''
	mask = 2**(num_bits - 1) - 1
	return -(input_value & mask) + (input_value & ~mask)

In [14]:
twos_complement(10,8)

-10

In [15]:
def twos_comp(val, bits):
    """compute the 2's complement of int value val"""
    if (val & (1 << (bits - 1))) != 0: # if sign bit is set e.g., 8bit: 128-255
        val = val - (1 << bits)        # compute negative value
    return val                         # return positive value as is

In [17]:
binary_string = '1111' # or whatever... no '0b' prefix
out = twos_comp(int(binary_string,2), len(binary_string))

In [18]:
out

-1