In [1]:
import torch

In [19]:
def int2bin(input, num_bits):
    mask = 2**num_bits - 1
    output = input.clone()
    output[input.lt(0)] = 2**(num_bits) + output[input.lt(0)]
    return output
    
def bin2int(input_value, num_bits):
    '''
    convert an unsigned input integer to a two's complement signed interger.
    Calculates a two's complement integer from the given input value's bits.
    '''
    mask = 2**(num_bits - 1) -1
    return -(input_value & ~mask) + (input_value & mask)

In [29]:
x_int = torch.Tensor([0, 1, 2, 3, -4, -3, -2, -1])
tmp = int2bin(x_int.char(),3)
print(tmp)

tensor([0, 1, 2, 3, 4, 5, 6, 7], dtype=torch.int8)


In [30]:
bin2int(tmp, 3)

tensor([ 0,  1,  2,  3, -4, -3, -2, -1], dtype=torch.int8)

In [32]:
# other testbenchs
x_int = torch.Tensor([126, 127, -128, -127, -126, -2, -1])
tmp = int2bin(x_int,8)
print(tmp)

tensor([126., 127., 128., 129., 130., 254., 255.])


In [33]:
bin2int(tmp.char(), 8).float() == x_int

tensor([1, 1, 1, 1, 1, 1, 1], dtype=torch.uint8)

In [34]:
x = torch.rand(64,3,3,3)

In [36]:
x.view(-1).

tensor([0.6309, 0.3736, 0.8705,  ..., 0.5366, 0.6102, 0.1138])

In [65]:
x = torch.rand(4)
print(x)

tensor([0.5674, 0.9832, 0.5973, 0.6154])


In [71]:
y = torch.rand(8).unsqueeze(-1)
print(y)

tensor([[0.3486],
        [0.6658],
        [0.6447],
        [0.1507],
        [0.0484],
        [0.9813],
        [0.2762],
        [0.8557]])


In [72]:
(x * y)

tensor([[0.1978, 0.3427, 0.2082, 0.2145],
        [0.3777, 0.6545, 0.3977, 0.4097],
        [0.3658, 0.6339, 0.3851, 0.3968],
        [0.0855, 0.1482, 0.0900, 0.0928],
        [0.0275, 0.0476, 0.0289, 0.0298],
        [0.5568, 0.9648, 0.5861, 0.6039],
        [0.1567, 0.2715, 0.1650, 0.1700],
        [0.4855, 0.8413, 0.5111, 0.5266]])

In [74]:
N_bits = 8
t = torch.arange(start=N_bits-1, end=-1, step=-1).unsqueeze(-1)
print(t)

tensor([[7],
        [6],
        [5],
        [4],
        [3],
        [2],
        [1],
        [0]])


In [75]:
b_w = 2**t

In [76]:
b_w[0] = -b_w[0]

In [77]:
b_w

tensor([[-128],
        [  64],
        [  32],
        [  16],
        [   8],
        [   4],
        [   2],
        [   1]])